[package]
name = "mpv-subs-popout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpvipc = "1.2.2"
gtk = "0.17.1"
